version: 1
builds:
  - id: default
    main: .
    binary: go-proj
    envs:
      - GOOS
      - GOARCH
archives:
  - id: default
    builds: ["default"]
    format: tar.gz
    wrap_in_directory: true
