name: SLSA Go Release
on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  id-token: write   # sign provenance
  contents: write   # upload assets
  actions: read

jobs:
  build-slsa3:
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.0.0
    with:
      go-version: "1.24.1"          # match your go.mod
      config-file: .slsa-goreleaser.yml
      # upload-assets: true         # default is true for tag pushes