name: SLSA Go Release
on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  id-token: write   # To sign the provenance
  contents: write   # To upload assets
  actions: read     # To read workflow identity

jobs:
  # Add this job to set dynamic values
  vars:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.slsa-vars.outputs.version }}
      commit: ${{ steps.slsa-vars.outputs.commit }}
      commit_date: ${{ steps.slsa-vars.outputs.commit_date }}
      tree_state: ${{ steps.slsa-vars.outputs.tree_state }}
    steps:
      - id: slsa-vars
        run: |
          # The version is the Git tag name, without the 'v' prefix
          echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
          
          # The commit hash from the checkout
          echo "commit=${{ github.sha }}" >> "$GITHUB_OUTPUT"
          
          # The commit date in RFC3339 format
          echo "commit_date=$(git show -s --format=%cI ${{ github.sha }})" >> "$GITHUB_OUTPUT"
          
          # Tree state should be 'clean' for official builds
          echo "tree_state=clean" >> "$GITHUB_OUTPUT"

  build-slsa3:
    # This job needs the outputs from the 'vars' job
    needs: [vars]
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.0.0
    with:
      go-version: "1.24.1"
      config-file: .slsa-goreleaser.yml
      # Pass the dynamic values to the builder
      evaluated-envs: >-
        VERSION=${{ needs.vars.outputs.version }}
        COMMIT=${{ needs.vars.outputs.commit }}
        COMMIT_DATE=${{ needs.vars.outputs.commit_date }}
        TREE_STATE=${{ needs.vars.outputs.tree_state }}
      # upload-assets: true # default is true for tag pushes