name: CI build and verify

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Build and test
        run: |
          go test ./...
          go build ./...

      - name: Pull verifier image
        run: docker pull exactlyprateek/verifier:03

      - name: Run verifier
        run: |
          docker run --rm \
            exactlyprateek/verifier:03 \
            -print-report "https://github.com/${{ github.repository }}"
